baseURL = "https://warmwinters.org"
enableEmoji = true
googleAnalytics = "UA-36603722-7"
languageCode = "en-us"
layoutDir = "src/html"
publishDir = "dist"
staticDir = "build"
taxonomies = []
title = "Warm Winters"

[params]
  description = "Our mission is to improve the lives of those living on the streets through the power of youth."
  image = "https://warmwinters.org/img/social.jpg"
  themeColor = "#fff"

[permalinks]
  page = "/:slug/"

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]
